apiVersion: v1
kind: Service
metadata:
  name: mongoexpress
spec:
  type: LoadBalancer
  selector:
    app: mongoexpress
  ports:
  - port: 8081
    targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress
spec:
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      restartPolicy: Always
      containers:
      - name: mongoexpress
        image: mongo-express
        resources:
          limits:
            memory: "108Mi"
            cpu: "100m"
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongo-root-password
          
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo




